[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.29'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "test/tables" }]

[fuzz]
runs = 5000

[profile.coverage.fuzz]
runs = 100

[profile.pr-ci.fuzz]
runs = 10000

[profile.master-ci.fuzz]
runs = 500000

[invariant]
runs             = 3
depth            = 5_000
fail_on_revert   = true
shrink_run_limit = 50
show_metrics     = true
show_solidity    = true

[profile.pr-ci.invariant]
runs             = 5
depth            = 10_000
fail_on_revert   = true
shrink_run_limit = 50
show_metrics     = true
show_solidity    = true

[profile.master-ci.invariant]
runs             = 50
depth            = 100_000
fail_on_revert   = true
shrink_run_limit = 50
show_metrics     = true
show_solidity    = true
timeout          = 18_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
