[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.29'
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 5000

[profile.ci.fuzz]
runs = 500000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
