[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.29'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "test/tables" }]

[fuzz]
runs = 5000

[profile.coverage.fuzz]
runs = 100

[profile.pr-ci.fuzz]
runs = 10000

[profile.master-ci.fuzz]
runs = 500000

[invariant]
runs             = 3      # The number of times to run the invariant tests
depth            = 10_000 # The number of calls to make in the invariant tests
fail_on_revert   = true   # Fail the invariant test if an error occurs
shrink_run_limit = 50     # The number of times to shrink the invariant test
show_metrics     = true   # Show the metrics of the invariant test
show_solidity    = true   # Show the solidity code of the invariant test

[profile.pr-ci.invariant]
runs             = 50      # The number of times to run the invariant tests
depth            = 10_000  # The number of calls to make in the invariant tests
fail_on_revert   = true    # Fail the invariant test if an error occurs
shrink_run_limit = 50      # The number of times to shrink the invariant test
show_metrics     = true    # Show the metrics of the invariant test
show_solidity    = true    # Show the solidity code of the invariant test

[profile.master-ci.invariant]
runs             = 50       # The number of times to run the invariant tests
depth            = 100_000  # The number of calls to make in the invariant tests
fail_on_revert   = true     # Fail the invariant test if an error occurs
shrink_run_limit = 50       # The number of times to shrink the invariant test
show_metrics     = true     # Show the metrics of the invariant test
show_solidity    = true     # Show the solidity code of the invariant test
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
