[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.29'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "test/tables" }]

[fuzz]
runs = 5000

[profile.ci.fuzz]
runs = 5000 # TODO: Increase

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
